# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: true
gui:
  scrollHeight: 15
